security:
    # Определяем, откуда брать пользователей
    providers:
        app_user_provider:
            entity:
                class: Kamalo\KanbanTaskManagementSystem\Domain\Entity\User
                property: email

    # Настройка паролей
    password_hashers:
        Kamalo\KanbanTaskManagementSystem\Domain\Entity\User:
            algorithm: auto

    firewalls:
        # отключаем защиту для дев тулов
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # отдельный firewall для логина
        login:
            pattern: ^/api/auth/login
            stateless: true

        # основной API firewall
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        # открытые роуты
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/projects/13/tasks, roles: PUBLIC_ACCESS }
        # всё остальное в API требует авторизации
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
